const grammarList = [
    // { name: "", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>"},
    { name: "Dạng A不A (câu hỏi Khẳng định - Phủ định)", mean: "Trong tiếng Trung, có một dạng ngữ pháp đặc trưng để hỏi Yes/No: [Chủ ngữ] + [A不A câu hỏi] + [Động từ + Tân ngữ]", example1: "王先生要不要喝咖啡？ <br/> (Wáng xiānsheng yào bù yào hē kāfēi?) <br/> Ông Vương có muốn uống cà phê không?", example2: "這是不是烏龍茶？ <br/> (Zhè shì bú shì Wūlóng chá?) <br/> Đây có phải là trà Ô Long không?", example3: "臺灣人喜歡不喜歡喝茶？ <br/> (Táiwān rén xǐhuān bù xǐhuān hē chá?) <br/> Người Đài Loan có thích uống trà hay không?" },
    { name: "Câu hỏi với 嗎 (ma)", mean: "Dùng 嗎 (ma) để biến một câu trần thuật thành một câu hỏi Yes/No. Không thay đổi trật tự câu. Chỉ cần thêm 嗎 vào cuối. Trả lời thường là 是/不是 (đúng/không) hoặc lặp lại động từ chính.", example1: "你好嗎？<br/> (Nǐ hǎo ma?) <br/> Bạn có khỏe không?", example2: "你來接我們嗎？ <br/> (Nǐ lái jiē wǒmen ma?) <br/> Bạn đến đón chúng tôi à?", example3: "他是日本人嗎？ <br/> (Tā shì Rìběn rén ma?) <br/> Anh ấy là người Nhật phải không?" },
    { name: "Trả lời phủ định với 不", mean: "不 (bù) là một phó từ phủ định, luôn đứng trước động từ hoặc tính từ. Khi muốn trả lời phủ định, người Trung thường lặp lại động từ ở dạng phủ định.", example1: "他是不是李先生？<br /> Khẳng định: 對，他是李先生。<br/> phủ định: 不是， 他不是李先生 <br/>", example2: "王先生喝茶嗎？<br/> Khẳng định: 是，他喝茶 <br/> phủ định: 不，他不喝  <br/>", example3: "李小姐是不是臺灣人？<br/> Khẳng định: 是，她是臺灣人。 <br/> Phủ định: 不 是，李小姐不是臺灣人  <br/>" },
    { name: "Trả lời câu hỏi", mean: "Ta có thể trả lời câu hỏi đầy đủ hoặc ngắn gọn", example1: "你是王先生嗎 ?<br/> Khẳng định: 是 hoặc 是的<br/> Đầy đủ: 對, 我就是王先生 <br/> Phủ định: 不是 <br/> Đầy đủ: 不是，我不是王先生", example2: "他來不來臺灣? <br/>Khẳng định: 來 hoặc 他來 <br/> đầy đủ: 對，他要來臺灣 <br/> Phủ định: 他不來 <br /> đầy đủ: 不，他不來臺灣", example3: "他喜歡不喜歡喝茶？<br/> Khẳng định: 喜歡 hoặc 他喜歡 <br/> đầy đủ: 對，他很喜歡喝茶 <br /> phủ định: 他不喜歡 <br /> đầy đủ: 不，他不喜歡喝茶  " },
    { name: "很 (hěn) + tính từ (stative verb)", mean: "Nghĩa là rất", example1: "烏龍茶很好喝 。", example2: "他很喜歡日本人 。", example3: "我們很好 。" },
    { name: "trợ từ ngữ khí 呢 (ne)", mean: "thường dùng để tạo câu hỏi ngắn kiểu 'còn … thì sao?'. Chủ ngữ + 呢？ Mệnh đề + 呢？ S + v + O, S2 + 呢？", example1: "我要喝茶， 你呢？", example2: "他不喝咖啡， 陳小姐呢？", example3: "王先生是日本人，李先生呢？" },
    { name: "👉 Đây là một ngữ pháp về phương vị từ và động từ trong tiếng Trung, thường gặp với các chữ: 上, 下, 裡, 外, 前, 後.", mean: "", example1: "<br/> <br/>", example2: "<br/> <br/>", example3: "<br/> <br/>" },
    { name: "3 (thanh 3) + 3 (thanh 3) → 2 + 3", mean: "Khi hai âm tiết có thanh 3 đứng cạnh nhau, âm tiết đầu đổi sang thanh 2.", example1: "你好 → ní hǎo", example2: "我很好 → wó hén hǎo", example3: "你也好 → ní yě hǎo" },
    { name: "一 (yī) + thanh 4 → yí (thanh 2)", mean: "Chữ 一 khi đứng trước âm tiết có thanh 4 sẽ đổi từ thanh 1 sang thanh 2.", example1: "一个 → yí gè", example2: "一次 → yí cì", example3: "一份 → yí fèn" },
    { name: "一 (yī) + thanh 1, 2, 3 → yì (thanh 4)", mean: "Chữ 一 khi đứng trước âm tiết mang thanh 1, 2, hoặc 3 sẽ đổi thành thanh 4.", example1: "一天 → yì tiān", example2: "一年 → yì nián", example3: "一条 → yì tiáo" },
    { name: "不 (bù) + thanh 4 → bú (thanh 2)", mean: "Chữ 不 khi đứng trước âm tiết có thanh 4 sẽ đổi thành thanh 2.", example1: "不是 → bú shì", example2: "不要 → bú yào", example3: "不对 → bú duì" },
    { name: "不 (bù) + thanh 1, 2, 3 → giữ thanh 4", mean: "Chữ 不 giữ nguyên thanh 4 khi đi với âm tiết không phải thanh 4.", example1: "不行 → bù xíng", example2: "不错 → bù cuò", example3: "不忙 → bù máng" },
    { name: "Liên tiếp nhiều thanh 3 → chỉ giữ thanh 3 ở cuối", mean: "Khi có nhiều âm tiết thanh 3 liên tiếp, các âm trước đổi sang thanh 2, chỉ âm cuối giữ thanh 3.", example1: "你我好 → ní wó hǎo", example2: "我也很好 → wó yé hén hǎo", example3: "你想我吗 → ní xiáng wǒ ma" },
    { name: "Thanh nhẹ (輕聲 qīng shēng)", mean: "Thanh nhẹ không mang dấu, đọc ngắn và nhẹ, thường dùng ở âm tiết cuối.", example1: "妈妈 → māma", example2: "朋友 → péngyou", example3: "什么 → shénme" },
    { name: "一 + động từ (ý nghĩa 'ngay lập tức')", mean: "Khi 一 đứng trước động từ, thường đọc là yí (thanh 2), biểu thị hành động diễn ra ngay.", example1: "一看 → yí kàn", example2: "一听 → yí tīng", example3: "一说 → yí shuō" },
    { name: "不 + 想 / 喜歡 / 知道", mean: "不 giữ thanh 4 vì theo sau là thanh 3 hoặc 1, 2.", example1: "不想 → bù xiǎng", example2: "不喜欢 → bù xǐhuān", example3: "不知道 → bù zhīdào" }
];