
const personNameData = [
    //    { chinese: "", mean: "", pronunciation: "", pinyin: "" },
    { chinese: "開", mean: "mở; bật; mở ra", pronunciation: "khai", pinyin: "kāi" },
    { chinese: "文", mean: "chữ; văn tự; tiếng; ngôn ngữ", pronunciation: "quển", pinyin: "wén " },
    { chinese: "開文", mean: "Khai Văn", pronunciation: "khai quển", pinyin: "Kāi wén " },
    { chinese: "王", mean: "Vương (Vua)", pronunciation: "quảng", pinyin: "wáng " },
    { chinese: "阮", mean: "Họ Nguyễn", pronunciation: "Roản", pinyin: "ruǎn" },
    { chinese: "陳", mean: "Họ trần", pronunciation: "trấn", pinyin: "chén" },
    { chinese: "黎", mean: "Họ Lê", pronunciation: "lí", pinyin: "lí" },
    { chinese: "範", mean: "Họ Phạm", pronunciation: "Phan", pinyin: "fàn" },
    { chinese: "黃", mean: "Họ Hoàng", pronunciation: "Hoáng", pinyin: "huáng " },
    { chinese: "潘", mean: "Phan", pronunciation: "pan", pinyin: "pān" },
    { chinese: "明", mean: "Minh (làm rõ, sáng tỏ, hiểu biết)", pronunciation: "míng", pinyin: "míng" },
    { chinese: "英", mean: "Anh (nước Anh)", pronunciation: "ding", pinyin: "yīng" },
    { chinese: "輝", mean: "Huy (sáng sủa)", pronunciation: "huy", pinyin: "huī " },
    { chinese: "光", mean: "Quang (Ánh sáng)", pronunciation: "quang", pinyin: "guāng" },
    { chinese: "德", mean: "Đức (đạo đức)", pronunciation: "tửa", pinyin: "dé" },
    { chinese: "維", mean: "Duy (gìn giữ, bảo quản)", pronunciation: "quẩy", pinyin: "wéi" },
    { chinese: "香", mean: "Hương (mùi hương, hương thơm)", pronunciation: "xeng", pinyin: "xiāng" },
    { chinese: "玉", mean: "Ngọc (ngọc thạch, bảo thạch)", pronunciation: "duy", pinyin: "yù" },
    { chinese: "幸", mean: "Hạnh (hạnh phúc)", pronunciation: "xìng", pinyin: "xìng" },
    { chinese: "靈", mean: "Linh (Linh hồn)", pronunciation: "lỉng", pinyin: "líng" },
    { chinese: "莊", mean: "Trang (Thôn trang, trang viên)", pronunciation: "troang", pinyin: "zhuāng" },
    { chinese: "蘭", mean: "Lan (Hoa lan)", pronunciation: "lán", pinyin: "lán" },
    { chinese: "盛", mean: "Thịnh (Hưng Thịnh)", pronunciation: "shèng", pinyin: "shèng" },
    { chinese: "黎國盛", mean: "Lê Quốc Thịnh", pronunciation: "Líguóshèng", pinyin: "Líguóshèng" },
];