/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
const vocabulary = [
    { chinese: "你好", mean: "Xin chào", pronunciation: "Nỉ hảo", pinyin: "Nǐ hǎo" },
    //   { chinese: "谢谢", mean: "Cảm ơn", pronunciation: "Xiè xiè", pinyin: "Xièxie" },
    //   { chinese: "再见", mean: "Tạm biệt", pronunciation: "Chai chiện", pinyin: "Zàijiàn" },
    //   { chinese: "请", mean: "Làm ơn / Mời", pronunciation: "Chǐng", pinyin: "Qǐng" },
    //   { chinese: "对不起", mean: "Xin lỗi", pronunciation: "Tuây pu chỉ", pinyin: "Duìbùqǐ" },
    //   { chinese: "没关系", mean: "Không sao", pronunciation: "Mấy quan xi", pinyin: "Méi guānxi" },
    //   { chinese: "早上好", mean: "Chào buổi sáng", pronunciation: "Zảo shàng hảo", pinyin: "Zǎoshang hǎo" },
    //   { chinese: "晚上好", mean: "Chào buổi tối", pronunciation: "Uẳn shàng hảo", pinyin: "Wǎnshang hǎo" },
    //   { chinese: "请问", mean: "Cho hỏi", pronunciation: "Chǐng uấn", pinyin: "Qǐngwèn" },
    //   { chinese: "厕所", mean: "Nhà vệ sinh", pronunciation: "Thứa sủa", pinyin: "Cèsuǒ" },
    //   { chinese: "", mean: "", pronunciation: "", pinyin: "" },
    //   ... thêm tiếp cho đến 1000 mục
    //    { chinese: "", mean: "", pronunciation: "", pinyin: "" },
    { chinese: "一", mean: "Số một", pronunciation: "Di", pinyin: "Yī" },
    { chinese: "二", mean: "Số hai", pronunciation: "Ơ", pinyin: "Èr" },
    { chinese: "三", mean: "Số ba", pronunciation: "Xan", pinyin: "Sān" },
    { chinese: "四", mean: "Số bốn", pronunciation: "Xư", pinyin: "Sì" },
    { chinese: "五", mean: "Số năm", pronunciation: "Ủ", pinyin: "wǔ" },
    { chinese: "六", mean: "Số sáu", pronunciation: "liêu", pinyin: "liù" },
    { chinese: "七", mean: "Số bảy", pronunciation: "Chi", pinyin: "qī" },
    { chinese: "八", mean: "Số tám", pronunciation: "Ba", pinyin: "bā" },
    { chinese: "九", mean: "Số Chín", pronunciation: "chiểu", pinyin: "jiǔ" },
    { chinese: "十", mean: "Số mười", pronunciation: "sử", pinyin: "shí" },
    { chinese: "十一", mean: "Mười một", pronunciation: "Sử di", pinyin: "Shíyī" },
    { chinese: "二十", mean: "Hai mươi", pronunciation: "Ơ sử", pinyin: "Èrshí" },
    { chinese: "三十", mean: "Ba mươi", pronunciation: "San sử", pinyin: "Sānshí" },
    { chinese: "四十", mean: "Bốn mươi", pronunciation: "Sư sử", pinyin: "Sìshí" },
    { chinese: "五十", mean: "Năm mươi", pronunciation: "Ủ sử", pinyin: "Wǔshí" },
    { chinese: "六十", mean: "Sáu mươi", pronunciation: "Liêu sử", pinyin: "Liùshí" },
    { chinese: "七十", mean: "Bảy mươi", pronunciation: "Chi sử", pinyin: "Qīshí" },
    { chinese: "八十", mean: "Tám mươi", pronunciation: "Ba sử", pinyin: "Bāshí" },
    { chinese: "九十", mean: "Chín mươi", pronunciation: "Chiu sử", pinyin: "Jiǔshí" },
    { chinese: "一百", mean: "Một trăm", pronunciation: "I bải", pinyin: "Yībǎi" },
    { chinese: "一百零一", mean: "Một trăm lẻ một", pronunciation: "I bải líng i", pinyin: "Yībǎi líng yī" },
    { chinese: "一百一十一", mean: "Một trăm mười một", pronunciation: "I bải i sư i", pinyin: "Yībǎi yīshí yī" },
    { chinese: "大", mean: "To lớn", pronunciation: "Ta", pinyin: "Dà" },
    { chinese: "口", mean: "Cái miệng", pronunciation: "Khẩu", pinyin: "Kǒu" },
    { chinese: "白", mean: "Màu trắng", pronunciation: "Bái", pinyin: "Bái" },
    { chinese: "不", mean: "Không", pronunciation: "Bu", pinyin: "Bù" },
    { chinese: "马", mean: "Con ngựa", pronunciation: "Mạ", pinyin: "Mǎ" },
    { chinese: "女", mean: "Nữ giới", pronunciation: "Nủy", pinyin: "Nǚ" },
    { chinese: "你", mean: "Bạn/cậu/mày", pronunciation: "Nỉ", pinyin: "Nǐ" },
    { chinese: "男", mean: "Nam giới", pronunciation: "Nán", pinyin: "Nán" },
    { chinese: "忙", mean: "Bận", pronunciation: "máng", pinyin: "Máng" },
    { chinese: "吗", mean: "Trợ từ nghi vấn/ ...không?", pronunciation: "Ma", pinyin: "Ma" },
    { chinese: "很", mean: "rất", pronunciation: "Khểnh", pinyin: "Hěn" },
    { chinese: "汉", mean: "Chữ Hán/dân tộc Hán/ Trung quốc", pronunciation: "Han", pinyin: "Hàn" },
    { chinese: "语", mean: "Ngữ/ngôn ngữ", pronunciation: "Dĩ", pinyin: "Yǔ" },
    { chinese: "太", mean: "quá", pronunciation: "Tai", pinyin: "Tài" },
    { chinese: "爸爸", mean: "Bố/ba", pronunciation: "Ba bà", pinyin: "Bàba" },
    { chinese: "妈妈", mean: "Mẹ", pronunciation: "Ma mà", pinyin: "妈妈" },
    { chinese: "哥哥", mean: "Anh trai", pronunciation: "Cưa cừa", pinyin: "Gēgē" },
    { chinese: "弟弟", mean: "Em trai", pronunciation: "Đi đì", pinyin: "Dìdì" },
    { chinese: "姐姐", mean: "Chị gái", pronunciation: "Chìa chia", pinyin: "Jiějiě" },
    { chinese: "妹妹", mean: "Em gái", pronunciation: "Mây mầy", pinyin: "Mèimei" },
    { chinese: "他", mean: "Anh ấy, ông ấy, chú ấy", pronunciation: "Ta (nam)", pinyin: "Tā" },
    { chinese: "她", mean: "Chị ấy, bà ấy, cô ấy", pronunciation: "Ta (nữ)", pinyin: "Tā" },
    { chinese: "的", mean: "Của", pronunciation: "Đơ", pinyin: "de" },
    { chinese: "人 (亻)", mean: "Người (nhân)", pronunciation: "rấn (nhân)", pinyin: "rén (nhân)" },
    { chinese: "刀 (刂)", mean: "dao (đao)", pronunciation: "tao (đao)", pinyin: "dāo (đao)" },
    { chinese: "力 ()", mean: "sức mạnh (lực)", pronunciation: "lị (lực)", pinyin: "lì (lực)" },
    { chinese: "口 ()", mean: "miệng (khẩu)", pronunciation: "khẩu (khẩu)", pinyin: "kǒu (khẩu)" },
    { chinese: "囗 ()", mean: "vây quanh (vi)", pronunciation: "uây (vi)", pinyin: "wéi (vi)" },
    { chinese: "土 ()", mean: "đất (thổ)", pronunciation: "thủ (thổ)", pinyin: "tǔ (thổ)" },
    { chinese: "大 ()", mean: "To lớn (đại)", pronunciation: "ta (đại)", pinyin: "dà (đại)" },
    { chinese: "女 ()", mean: "nữ (nữ)", pronunciation: "nủy (nữ)", pinyin: "nǚ (nữ)" },
    { chinese: "宀 ()", mean: "máy nhà (miên)", pronunciation: "miền (miên)", pinyin: "mián (miên)" },
    { chinese: "山 ()", mean: "núi (sơn)", pronunciation: "san (sơn)", pinyin: "shān (sơn)" },
    { chinese: "巾 ()", mean: "khăn (cân)", pronunciation: "chin (cân)", pinyin: "jīn (cân)" },
    { chinese: "广 ()", mean: "máy nhà (nghiễm)", pronunciation: "quảng (nghiễm)", pinyin: "guǎng (nghiễm)" },
    { chinese: "彳()", mean: "bước chân (xích)", pronunciation: "chừ (xích)", pinyin: "chì (xích)" },
    { chinese: "心 (忄)", mean: "tim (tâm)", pronunciation: "xin (tâm)", pinyin: "xīn (tâm)" },
    { chinese: "手 (扌)", mean: "tay (thủ)", pronunciation: "sẩu (thủ)", pinyin: "shǒu (thủ)" },
    { chinese: "攴 (攵)", mean: "đánh (phộc)", pronunciation: "pu (phộc)", pinyin: "pū (phộc)" },
    { chinese: "日 ()", mean: "mặt trời (nhật)", pronunciation: "rư (nhật)", pinyin: "rì (nhật)" },
    { chinese: "木 ()", mean: "cây (mộc)", pronunciation: "mù (mộc)", pinyin: "mù (mộc)" },
    { chinese: "水 (氵)", mean: "nước (thủy)", pronunciation: "suẩy (thủy)", pinyin: "shuǐ (thủy)" },
    { chinese: "火 (灬)", mean: "lửa (hỏa)", pronunciation: "hủa (hỏa)", pinyin: "huǒ (hỏa)" },
    { chinese: "牛 ()", mean: "trâu (ngưu)", pronunciation: "níu (ngưu)", pinyin: "níu (ngưu)" },
    { chinese: "犬 (犭)", mean: "chó (khuyển)", pronunciation: "chuyển (khuyển)", pinyin: "quǎn (khuyển)" },
    { chinese: "玉 ()", mean: "ngọc (ngọc)", pronunciation: "duy (ngọc)", pinyin: "yù (ngọc)" },
    { chinese: "田 ()", mean: "ruộng (điền)", pronunciation: "thiển (điền)", pinyin: "tián (điền)" },
    { chinese: "疒 ()", mean: "bệnh (nạch)", pronunciation: "nơ (nạch)", pinyin: "nì (nạch)" },
    { chinese: "目 ()", mean: "mắt (mục)", pronunciation: "mu (mục)", pinyin: "mù (mục)" },
    { chinese: "石 ()", mean: "đá (thạch)", pronunciation: "sỉ (thạch)", pinyin: "shí (thạch)" },
    { chinese: "禾 ()", mean: "lúa (hòa)", pronunciation: "Khửa (hòa)", pinyin: "hé (hòa)" },
    { chinese: "竹 ()", mean: "tre (trúc)", pronunciation: "chú (trúc)", pinyin: "zhú (trúc)" },
    { chinese: "米 ()", mean: "gạo (mễ)", pronunciation: "mỉ (mễ)", pinyin: "mǐ (mễ)" },
    { chinese: "糸 (纟)", mean: "tơ (mịch)", pronunciation: "mì (mịch)", pinyin: "mì (mịch)" },
    { chinese: "肉 (月)", mean: "thịt (nhục)", pronunciation: "rou -> rẩu (nhục)", pinyin: "ròu (nhục)" },
    { chinese: "艸 (艹)", mean: "cỏ (thảo)", pronunciation: "thảo (thảo)", pinyin: "cǎo (thảo)" },
    { chinese: "虫 ()", mean: "côn trùng (trùng)", pronunciation: "chủng (trùng)", pinyin: "chóng (trùng)" },
    { chinese: "衣 (衤)", mean: "áo (y)", pronunciation: "i (y)", pinyin: "yī (y)" },
    { chinese: "言 ()", mean: "lời nói (ngôn)", pronunciation: "dẻn (ngôn)", pinyin: "yán (ngôn)" },
    { chinese: "貝 ()", mean: "vỏ sò (bối)", pronunciation: "bây (bối)", pinyin: "bèi (bối)" },
    { chinese: "足 ()", mean: "chân (túc)", pronunciation: "chú (túc)", pinyin: "zú (túc)" },
    { chinese: "車 ()", mean: "xe (xa)", pronunciation: "trưa (xa)", pinyin: "chē (xa)" },
    { chinese: "辶 ()", mean: "bước (sước)", pronunciation: "chua (sước)", pinyin: "chuò (sước)" },
    { chinese: "邑 (阝-phải)", mean: "làng (ấp)", pronunciation: "i (ấp)", pinyin: "yì (ấp)" },
    { chinese: "金 ()", mean: "kim loại (kim)", pronunciation: "chin (kim)", pinyin: "jīn (kim)" },
    { chinese: "門 ()", mean: "cửa (môn)", pronunciation: "mển (môn)", pinyin: "mén (môn)" },
    { chinese: "阜 (阝-trái)", mean: "đất cao (phụ)", pronunciation: "phu (phụ)", pinyin: "fù (phụ)" },
    { chinese: "雨 ()", mean: "mưa (vũ)", pronunciation: "dũy (vũ)", pinyin: "yǔ (vũ)" },
    { chinese: "頁 ()", mean: "đầu (hiệt)", pronunciation: "dia (hiệt)", pinyin: "yè (hiệt)" },
    { chinese: "食 ()", mean: "ăn (thực)", pronunciation: "sỉ (thực)", pinyin: "shí (thực)" },
    { chinese: "馬 ()", mean: "ngựa (mã)", pronunciation: "mã (mã)", pinyin: "mǎ (mã)" },
    { chinese: "魚 ()", mean: "cá (ngư)", pronunciation: "dũy (ngư)", pinyin: "yú (ngư)" },
    { chinese: "鳥 ()", mean: "chim (điểu)", pronunciation: "niểu (điểu)", pinyin: "niǎo (điểu)" },
    { chinese: "冖 ()", mean: "trùm, che (mịch)", pronunciation: "mì (mịch)", pinyin: "mì (mịch)" },
    { chinese: "冫 ()", mean: "băng, lạnh (băng)", pronunciation: "bing (băng)", pinyin: "bīng (băng)" },
    { chinese: "又 ()", mean: "lại, lần nửa (hựu)", pronunciation: "dâu (hựu)", pinyin: "yòu (hựu)" },
    { chinese: "夕 ()", mean: "buổi tối (tịch)", pronunciation: "xi (tịch)", pinyin: "xī (tịch)" },
    { chinese: "子 ()", mean: "con trai (tử)", pronunciation: "dư (tử)", pinyin: "zǐ (tử)" },
    { chinese: "小 ()", mean: "nhỏ, bé (tiểu)", pronunciation: "xiểu (tiểu)", pinyin: "xiǎo (tiểu)" },
    { chinese: "尸 ()", mean: "xác chết, thể xác (thi)", pronunciation: "si (thi)", pinyin: "shī (thi)" },
    { chinese: "工 ()", mean: "công việc, thợ, thủ công (công)", pronunciation: "cung (công)", pinyin: "gōng (công)" },
    { chinese: "干 ()", mean: "cái khiên, che, Khô, can dự (can)", pronunciation: "cang (can)", pinyin: "gān (can)" },
    { chinese: "幺 ()", mean: "út, bé nhỏ, thứ yếu (yêu)", pronunciation: "dao (yêu)", pinyin: "yāo (yêu)" },
    { chinese: "廴 ()", mean: "bước dài, dẫn đi (dẫn)", pronunciation: "dỉn (dẫn)", pinyin: "yǐn (dẫn)" },
    { chinese: "弓 ()", mean: "cây cung (cung)", pronunciation: "cung (cung)", pinyin: "gōng (cung)" },
    { chinese: "彡 ()", mean: "lông dài, tóc (sam)", pronunciation: "san (sam)", pinyin: "shān (sam)" },
    { chinese: "戈 ()", mean: "cây giáo, cây thương (qua)", pronunciation: "cưa (qua)", pinyin: "gē (qua)" },
    { chinese: "月 ()", mean: "mặt trăng (nguyệt)", pronunciation: "duya (nguyệt)", pinyin: "yuè (nguyệt)" },
    { chinese: "示 (礻)", mean: "chỉ thị, thần linh (liên quan đến cúng bái, tôn giáo) (thị)", pronunciation: "sì (thị)", pinyin: "shì (thị)" },
];