/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
const vocabulary = [
    //    { chinese: "", mean: "", pronunciation: "", pinyin: "" },
    { chinese: "你好", mean: "Xin chào", pronunciation: "Nỉ hảo", pinyin: "Nǐ hǎo" },
    { chinese: "一", mean: "Số một", pronunciation: "Di", pinyin: "Yī" },
    { chinese: "二", mean: "Số hai", pronunciation: "Ơ", pinyin: "Èr" },
    { chinese: "三", mean: "Số ba", pronunciation: "Xan", pinyin: "Sān" },
    { chinese: "四", mean: "Số bốn", pronunciation: "Xư", pinyin: "Sì" },
    { chinese: "五", mean: "Số năm", pronunciation: "Ủ", pinyin: "wǔ" },
    { chinese: "六", mean: "Số sáu", pronunciation: "liêu", pinyin: "liù" },
    { chinese: "七", mean: "Số bảy", pronunciation: "Chi", pinyin: "qī" },
    { chinese: "八", mean: "Số tám", pronunciation: "Ba", pinyin: "bā" },
    { chinese: "九", mean: "Số Chín", pronunciation: "chiểu", pinyin: "jiǔ" },
    { chinese: "十", mean: "Số mười", pronunciation: "sử", pinyin: "shí" },
    { chinese: "十一", mean: "Mười một", pronunciation: "Sử di", pinyin: "Shíyī" },
    { chinese: "二十", mean: "Hai mươi", pronunciation: "Ơ sử", pinyin: "Èrshí" },
    { chinese: "三十", mean: "Ba mươi", pronunciation: "San sử", pinyin: "Sānshí" },
    { chinese: "四十", mean: "Bốn mươi", pronunciation: "Sư sử", pinyin: "Sìshí" },
    { chinese: "五十", mean: "Năm mươi", pronunciation: "Ủ sử", pinyin: "Wǔshí" },
    { chinese: "六十", mean: "Sáu mươi", pronunciation: "Liêu sử", pinyin: "Liùshí" },
    { chinese: "七十", mean: "Bảy mươi", pronunciation: "Chi sử", pinyin: "Qīshí" },
    { chinese: "八十", mean: "Tám mươi", pronunciation: "Ba sử", pinyin: "Bāshí" },
    { chinese: "九十", mean: "Chín mươi", pronunciation: "Chiu sử", pinyin: "Jiǔshí" },
    { chinese: "一百", mean: "Một trăm", pronunciation: "I bải", pinyin: "Yībǎi" },
    { chinese: "一百零一", mean: "Một trăm lẻ một", pronunciation: "I bải líng i", pinyin: "Yībǎi líng yī" },
    { chinese: "一百一十一", mean: "Một trăm mười một", pronunciation: "I bải i sư i", pinyin: "Yībǎi yīshí yī" },
    { chinese: "大", mean: "To lớn", pronunciation: "Ta", pinyin: "Dà" },
    { chinese: "口", mean: "Cái miệng", pronunciation: "Khẩu", pinyin: "Kǒu" },
    { chinese: "白", mean: "Màu trắng, sáng", pronunciation: "Bái", pinyin: "Bái" },
    { chinese: "不", mean: "Không", pronunciation: "Bu", pinyin: "Bù" },
    { chinese: "馬", mean: "Con ngựa", pronunciation: "Mạ", pinyin: "Mǎ" },
    { chinese: "女", mean: "Nữ giới", pronunciation: "Nủy", pinyin: "Nǚ" },
    { chinese: "男", mean: "Nam giới", pronunciation: "Nán", pinyin: "Nán" },
    { chinese: "忙", mean: "Bận", pronunciation: "máng", pinyin: "Máng" },
    { chinese: "很", mean: "rất", pronunciation: "Khểnh", pinyin: "Hěn" },
    { chinese: "汉", mean: "Chữ Hán/dân tộc Hán/ Trung quốc", pronunciation: "Han", pinyin: "Hàn" },
    { chinese: "语", mean: "Ngữ/ngôn ngữ", pronunciation: "Dĩ", pinyin: "Yǔ" },
    { chinese: "太", mean: "quá", pronunciation: "Tai", pinyin: "Tài" },
    { chinese: "爸爸", mean: "Bố/ba", pronunciation: "Ba bà", pinyin: "Bàba" },
    { chinese: "媽媽", mean: "Mẹ", pronunciation: "Ma mà", pinyin: "妈妈" },
    { chinese: "哥哥", mean: "Anh trai", pronunciation: "Cưa cừa", pinyin: "Gēgē" },
    { chinese: "弟弟", mean: "Em trai", pronunciation: "Đi đì", pinyin: "Dìdì" },
    { chinese: "姐姐", mean: "Chị gái", pronunciation: "Chìa chia", pinyin: "Jiějiě" },
    { chinese: "妹妹", mean: "Em gái", pronunciation: "Mây mầy", pinyin: "Mèimei" },
    { chinese: "他", mean: "Anh ấy, ông ấy, chú ấy", pronunciation: "Ta (nam)", pinyin: "Tā" },
    { chinese: "她", mean: "Chị ấy, bà ấy, cô ấy", pronunciation: "Ta (nữ)", pinyin: "Tā" },
    { chinese: "的", mean: "Của", pronunciation: "Đơ", pinyin: "de" },
    { chinese: "人 (亻)", mean: "Người (nhân)", pronunciation: "rấn (nhân)", pinyin: "rén (nhân)" },
    { chinese: "刀 (刂)", mean: "dao (đao)", pronunciation: "tao (đao)", pinyin: "dāo (đao)" },
    { chinese: "力 ()", mean: "sức mạnh (lực)", pronunciation: "lị (lực)", pinyin: "lì (lực)" },
    { chinese: "口 ()", mean: "miệng (khẩu)", pronunciation: "khẩu (khẩu)", pinyin: "kǒu (khẩu)" },
    { chinese: "囗 ()", mean: "vây quanh (vi)", pronunciation: "uây (vi)", pinyin: "wéi (vi)" },
    { chinese: "土 ()", mean: "đất (thổ)", pronunciation: "thủ (thổ)", pinyin: "tǔ (thổ)" },
    { chinese: "大 ()", mean: "To lớn (đại)", pronunciation: "ta (đại)", pinyin: "dà (đại)" },
    { chinese: "女 ()", mean: "nữ (nữ)", pronunciation: "nủy (nữ)", pinyin: "nǚ (nữ)" },
    { chinese: "宀 ()", mean: "máy nhà (miên)", pronunciation: "miền (miên)", pinyin: "mián (miên)" },
    { chinese: "山 ()", mean: "núi (sơn)", pronunciation: "san (sơn)", pinyin: "shān (sơn)" },
    { chinese: "巾 ()", mean: "khăn (cân)", pronunciation: "chin (cân)", pinyin: "jīn (cân)" },
    { chinese: "广 ()", mean: "máy nhà (nghiễm)", pronunciation: "quảng (nghiễm)", pinyin: "guǎng (nghiễm)" },
    { chinese: "彳()", mean: "bước chân (xích)", pronunciation: "chừ (xích)", pinyin: "chì (xích)" },
    { chinese: "心 (忄)", mean: "tim (tâm)", pronunciation: "xin (tâm)", pinyin: "xīn (tâm)" },
    { chinese: "手 (扌)", mean: "tay (thủ)", pronunciation: "sẩu (thủ)", pinyin: "shǒu (thủ)" },
    { chinese: "攴 (攵)", mean: "đánh (phộc)", pronunciation: "pu (phộc)", pinyin: "pū (phộc)" },
    { chinese: "日 ()", mean: "mặt trời (nhật), ngày", pronunciation: "rư (nhật)", pinyin: "rì (nhật)" },
    { chinese: "木 ()", mean: "cây (mộc)", pronunciation: "mù (mộc)", pinyin: "mù (mộc)" },
    { chinese: "水 (氵)", mean: "nước (thủy)", pronunciation: "suẩy (thủy)", pinyin: "shuǐ (thủy)" },
    { chinese: "火 (灬)", mean: "lửa (hỏa)", pronunciation: "hủa (hỏa)", pinyin: "huǒ (hỏa)" },
    { chinese: "牛 ()", mean: "trâu (ngưu)", pronunciation: "níu (ngưu)", pinyin: "níu (ngưu)" },
    { chinese: "犬 (犭)", mean: "chó (khuyển)", pronunciation: "chuyển (khuyển)", pinyin: "quǎn (khuyển)" },
    { chinese: "玉 ()", mean: "ngọc (ngọc)", pronunciation: "duy (ngọc)", pinyin: "yù (ngọc)" },
    { chinese: "田 ()", mean: "ruộng (điền)", pronunciation: "thiển (điền)", pinyin: "tián (điền)" },
    { chinese: "疒 ()", mean: "bệnh (nạch)", pronunciation: "nơ (nạch)", pinyin: "nì (nạch)" },
    { chinese: "目 ()", mean: "mắt (mục)", pronunciation: "mu (mục)", pinyin: "mù (mục)" },
    { chinese: "石 ()", mean: "đá (thạch)", pronunciation: "sỉ (thạch)", pinyin: "shí (thạch)" },
    { chinese: "禾 ()", mean: "lúa (hòa)", pronunciation: "Khửa (hòa)", pinyin: "hé (hòa)" },
    { chinese: "竹 ()", mean: "tre (trúc)", pronunciation: "chú (trúc)", pinyin: "zhú (trúc)" },
    { chinese: "米 ()", mean: "gạo (mễ)", pronunciation: "mỉ (mễ)", pinyin: "mǐ (mễ)" },
    { chinese: "糸 (纟)", mean: "tơ (mịch)", pronunciation: "mì (mịch)", pinyin: "mì (mịch)" },
    { chinese: "肉 (月)", mean: "thịt (nhục)", pronunciation: "rou -> rẩu (nhục)", pinyin: "ròu (nhục)" },
    { chinese: "艸 (艹)", mean: "cỏ (thảo)", pronunciation: "thảo (thảo)", pinyin: "cǎo (thảo)" },
    { chinese: "虫 ()", mean: "côn trùng (trùng)", pronunciation: "chủng (trùng)", pinyin: "chóng (trùng)" },
    { chinese: "衣 (衤)", mean: "áo (y)", pronunciation: "i (y)", pinyin: "yī (y)" },
    { chinese: "言 ()", mean: "lời nói (ngôn)", pronunciation: "dẻn (ngôn)", pinyin: "yán (ngôn)" },
    { chinese: "貝 ()", mean: "vỏ sò (bối)", pronunciation: "bây (bối)", pinyin: "bèi (bối)" },
    { chinese: "足 ()", mean: "chân (túc)", pronunciation: "chú (túc)", pinyin: "zú (túc)" },
    { chinese: "車 ()", mean: "xe (xa)", pronunciation: "trưa (xa)", pinyin: "chē (xa)" },
    { chinese: "辶 ()", mean: "bước (sước)", pronunciation: "chua (sước)", pinyin: "chuò (sước)" },
    { chinese: "邑 (阝-phải)", mean: "làng (ấp)", pronunciation: "i (ấp)", pinyin: "yì (ấp)" },
    { chinese: "金 ()", mean: "kim loại (kim)", pronunciation: "chin (kim)", pinyin: "jīn (kim)" },
    { chinese: "門 ()", mean: "cửa (môn)", pronunciation: "mển (môn)", pinyin: "mén (môn)" },
    { chinese: "阜 (阝-trái)", mean: "đất cao (phụ)", pronunciation: "phu (phụ)", pinyin: "fù (phụ)" },
    { chinese: "雨 ()", mean: "mưa (vũ)", pronunciation: "dũy (vũ)", pinyin: "yǔ (vũ)" },
    { chinese: "頁 ()", mean: "đầu (hiệt)", pronunciation: "dia (hiệt)", pinyin: "yè (hiệt)" },
    { chinese: "食 ()", mean: "ăn (thực)", pronunciation: "sỉ (thực)", pinyin: "shí (thực)" },
    { chinese: "馬 ()", mean: "ngựa (mã)", pronunciation: "mã (mã)", pinyin: "mǎ (mã)" },
    { chinese: "魚 ()", mean: "cá (ngư)", pronunciation: "dũy (ngư)", pinyin: "yú (ngư)" },
    { chinese: "鳥 ()", mean: "chim (điểu)", pronunciation: "niểu (điểu)", pinyin: "niǎo (điểu)" },
    { chinese: "冖 ()", mean: "trùm, che (mịch)", pronunciation: "mì (mịch)", pinyin: "mì (mịch)" },
    { chinese: "冫 ()", mean: "băng, lạnh (băng)", pronunciation: "bing (băng)", pinyin: "bīng (băng)" },
    { chinese: "又 ()", mean: "lại, lần nửa (hựu)", pronunciation: "dâu (hựu)", pinyin: "yòu (hựu)" },
    { chinese: "夕 ()", mean: "buổi tối (tịch)", pronunciation: "xi (tịch)", pinyin: "xī (tịch)" },
    { chinese: "子 ()", mean: "con trai (tử)", pronunciation: "dư (tử)", pinyin: "zǐ (tử)" },
    { chinese: "小 ()", mean: "nhỏ, bé (tiểu)", pronunciation: "xiểu (tiểu)", pinyin: "xiǎo (tiểu)" },
    { chinese: "尸 ()", mean: "xác chết, thể xác (thi)", pronunciation: "si (thi)", pinyin: "shī (thi)" },
    { chinese: "工 ()", mean: "công việc, thợ, thủ công (công)", pronunciation: "cung (công)", pinyin: "gōng (công)" },
    { chinese: "干 ()", mean: "cái khiên, che, Khô, can dự (can)", pronunciation: "cang (can)", pinyin: "gān (can)" },
    { chinese: "幺 ()", mean: "út, bé nhỏ, thứ yếu (yêu)", pronunciation: "dao (yêu)", pinyin: "yāo (yêu)" },
    { chinese: "廴 ()", mean: "bước dài, dẫn đi (dẫn)", pronunciation: "dỉn (dẫn)", pinyin: "yǐn (dẫn)" },
    { chinese: "弓 ()", mean: "cây cung (cung)", pronunciation: "cung (cung)", pinyin: "gōng (cung)" },
    { chinese: "彡 ()", mean: "lông dài, tóc (sam)", pronunciation: "san (sam)", pinyin: "shān (sam)" },
    { chinese: "戈 ()", mean: "cây giáo, cây thương (qua)", pronunciation: "cưa (qua)", pinyin: "gē (qua)" },
    { chinese: "月 ()", mean: "mặt trăng (nguyệt)", pronunciation: "duya (nguyệt)", pinyin: "yuè (nguyệt)" },
    { chinese: "示 (礻)", mean: "chỉ thị, thần linh (liên quan đến cúng bái, tôn giáo) (thị)", pronunciation: "sì (thị)", pinyin: "shì (thị)" },
    { chinese: "你", mean: "Bạn/cậu/mày", pronunciation: "Nỉ", pinyin: "Nǐ" },
    { chinese: "來", mean: "đến, tới", pronunciation: "lái", pinyin: "lái" },
    { chinese: "是", mean: "là, phải", pronunciation: "sừ", pinyin: "shì" },
    { chinese: "小姐", mean: "chị, cô gái, Miss, Ms", pronunciation: "xảo chỉa", pinyin: "xiǎojiě " },
    { chinese: "先生", mean: "ông, Mr", pronunciation: "xuyên sâng", pinyin: "xiānsheng" },
    { chinese: "先", mean: "trước, trước tiên", pronunciation: "xuyên", pinyin: "xiān" },
    { chinese: "生", mean: "sinh ra", pronunciation: "sâng", pinyin: "shēng" },
    { chinese: "嗎", mean: "Trợ từ nghi vấn/ ...không?", pronunciation: "Ma", pinyin: "Ma" },
    { chinese: "接", mean: "nắm lấy, tiếp nhận, đón", pronunciation: "chia", pinyin: "jiē" },
    { chinese: "我們", mean: "chúng tôi, chúng ta", pronunciation: "vỏ men", pinyin: "wǒmen" },
    { chinese: "我", mean: "Tôi, ta", pronunciation: "vỏ", pinyin: "wǒ " },
    { chinese: "們", mean: "gắn sau đại từ hoặc danh từ chỉ người/động vật để biến thành số nhiều (không dùng cho đồ vật)", pronunciation: "men", pinyin: "men" },
    { chinese: "這", mean: "đây, cái này", pronunciation: "chừa", pinyin: "zhè" },
    { chinese: "好", mean: "Tốt, khỏe", pronunciation: "hảo", pinyin: "hǎo" },
    { chinese: "姓", mean: "Họ", pronunciation: "xìng", pinyin: "xìng" },
    { chinese: "叫", mean: "Kêu, gọi là, hét", pronunciation: "chi ào", pinyin: "jiào" },
    { chinese: "你們", mean: "các bạn, chúng mày, tụi mày, các cậu", pronunciation: "nỉ men", pinyin: "nǐmen" },
    { chinese: "臺灣 (台湾)", mean: "Đài Loan", pronunciation: "tải wan", pinyin: "táiwān" },
    { chinese: "歡", mean: "vui mừng, vui sướng", pronunciation: "hoan", pinyin: "huān" },
    { chinese: "迎", mean: "ghênh tiếp, nghênh đón", pronunciation: "dỉng", pinyin: "yíng" },
    { chinese: "歡迎", mean: "chào đón, chào mừng", pronunciation: "hoan dỉng", pinyin: "huānyíng" },
    { chinese: "請", mean: "mời, xin, please", pronunciation: "chỉng", pinyin: "qǐng" },
    { chinese: "問", mean: "hỏi", pronunciation: "wèn", pinyin: "wèn" },
    { chinese: "請問", mean: "xin hỏi, cho hỏi", pronunciation: "chỉn wèn", pinyin: "qǐngwèn" },
    { chinese: "是的", mean: "đúng vậy", pronunciation: "sư đờ", pinyin: "shì de" },
    { chinese: "謝謝", mean: "cảm ơn", pronunciation: "xia xỉa", pinyin: "xièxie" },
    { chinese: "客", mean: "Khách", pronunciation: "khưa", pinyin: "kè" },
    { chinese: "氣", mean: "Khí, không khí, hơi", pronunciation: "chì", pinyin: "qì" },
    { chinese: "不客氣", mean: "đừng khách sáo", pronunciation: "bủ khưa chì", pinyin: "bùkèqi" },
    { chinese: "喝", mean: "uống, drink", pronunciation: "khưa", pinyin: "hē" },
    { chinese: "茶", mean: "trà", pronunciation: "chá ", pinyin: "chá " },
    { chinese: "好喝", mean: "ngon khi uống", pronunciation: "Hảo khưa", pinyin: "hǎo hē" },
    { chinese: "什", mean: "nhiều loại, tạp, các thứ lặt vặt / kết hợp với 麼 -> cái gì", pronunciation: "sí / sấn", pinyin: "shí/shén" },
    { chinese: "麼", mean: "trợ từ cái gì ?", pronunciation: "ma", pinyin: "me" },
    { chinese: "什麼", mean: "cái gì ?", pronunciation: "sẩn mơ", pinyin: "shén me" },
    { chinese: "喜", mean: "vui mừng; hoan hỉ", pronunciation: "xỉ", pinyin: "xǐ" },
    { chinese: "喜歡", mean: "thích, ưa thích", pronunciation: "xỉ hoan", pinyin: "xǐhuan " },
    { chinese: "呢", mean: "trợ từ ngữ khí thường dùng ở cuối câu để biểu thị ý nhẹ nhàng, nhấn mạnh hoặc hỏi lại (còn ... ?)", pronunciation: "nơ", pinyin: "ne" },
    { chinese: "哪", mean: "nghĩa là “nào, cái nào, ở đâu”, thường dùng để đặt câu hỏi. (which)", pronunciation: "nả", pinyin: "nǎ" },
    { chinese: "要", mean: "muốn", pronunciation: "dào", pinyin: "yào" },
    { chinese: "咖啡", mean: "cà phê", pronunciation: "ka phê", pinyin: "kāfēi" },
    { chinese: "本", mean: "Gốc, rễ", pronunciation: "bển", pinyin: "běn" },
    { chinese: "日本", mean: "Nhật Bản", pronunciation: "ri bển", pinyin: "rìběn" },
    { chinese: "美", mean: "đẹp, mỹ lệ", pronunciation: "mẩy", pinyin: "měi" },
    { chinese: "國", mean: "quốc gia, đất nước", pronunciation: "gủa", pinyin: "guó" },
    { chinese: "美國", mean: "Nước mỹ", pronunciation: "mẩy gủa", pinyin: "Měiguó" },
    { chinese: "對", mean: "về, với, đối với, đúng, chính xác", pronunciation: "tuy", pinyin: "duì" },
    { chinese: "起", mean: "dậy, đứng dậy", pronunciation: "chỉ", pinyin: "qǐ" },
    { chinese: "烏", mean: "con quạ", pronunciation: "u", pinyin: "wū" },
    { chinese: "龍", mean: "con rồng", pronunciation: "lóng", pinyin: "lóng" },
    { chinese: "對不起", mean: "Xin lỗi", pronunciation: "duìbuqǐ", pinyin: "duìbuqǐ" },
    { chinese: "越", mean: "Việt (tên tộc Việt cổ ở phương Nam).", pronunciation: "duê", pinyin: "yuè" },
    { chinese: "南", mean: "nam; phía nam; hướng nam; phương nam [South]", pronunciation: "nán ", pinyin: "nán" },
    { chinese: "越南", mean: "Nước Việt Nam", pronunciation: "Yuènán", pinyin: "Yuènán" },
    { chinese: "家", mean: "nhà, ngôi nhà", pronunciation: "jiā", pinyin: "jiā" },
    { chinese: "家人", mean: "Gia đình", pronunciation: "jiārén", pinyin: "jiārén" },
    { chinese: "漂", mean: "trôi; nổi; dạt; lềnh bênh", pronunciation: "piāo", pinyin: "piāo" },
    { chinese: "亮", mean: "sáng; bóng", pronunciation: "liàng", pinyin: "liàng" },
    { chinese: "漂亮", mean: "đẹp; xinh xắn; xinh đẹp; có dáng", pronunciation: "piàoliang", pinyin: "piàoliang" },
    { chinese: "房", mean: "Nhà, căn nhà", pronunciation: "fáng", pinyin: "fáng" },
    { chinese: "房子", mean: "nhà; nhà cửa; cái nhà", pronunciation: "fángzi", pinyin: "fángzi" },
    { chinese: "坐", mean: "Ngồi", pronunciation: "zuò", pinyin: "zuò" },
    { chinese: "有", mean: "có; hữu (biểu thị sở hữu)", pronunciation: "yǒu", pinyin: "yǒu" },
    { chinese: "多", mean: "nhiều (many)", pronunciation: "duō", pinyin: "duō" },
    { chinese: "照", mean: "chiếu; soi; chiếu rọi, chụp", pronunciation: "zhào", pinyin: "zhào" },
    { chinese: "片", mean: "mảnh, tấm, thẻ (dùng cho vật mỏng, phẳng)", pronunciation: "piān", pinyin: "piān" },
    { chinese: "照片", mean: "tấm ảnh; bức ảnh; tấm hình", pronunciation: "zhàopiàn", pinyin: "zhàopiàn" },
    { chinese: "都", mean: "tất cả, đều, toàn bộ (all, both)", pronunciation: "dōu", pinyin: "dōu" },
    { chinese: "相", mean: "Hình dạng, diện mạo, tướng mạo / lẫn nhau; hỗ tương", pronunciation: "xiāng", pinyin: "xiāng" },
    { chinese: "照相", mean: "Chụp ảnh, chụp hình", pronunciation: "zhàoxiàng", pinyin: "zhàoxiàng" },
    { chinese: "張", mean: "Họ Trương / Mở ra, căng ra, trải ra / Đơn vị đo lường (lượng từ) → dùng cho vật phẳng, rộng như giấy, giường, bàn, ảnh…", pronunciation: "zhāng", pinyin: "zhāng" },
    { chinese: "看", mean: "nhìn; xem; coi; đọc", pronunciation: "kàn", pinyin: "kàn" },
    { chinese: "好看", mean: "đẹp; coi được; xinh; xinh đẹp; đẹp đẽ; đẹp mắt (good looking)", pronunciation: "hǎokàn", pinyin: "hǎokàn" },
    { chinese: "誰", mean: "ai (who)", pronunciation: "shuí", pinyin: "shuí" },
    { chinese: "進", mean: "đi vào, vô, tiến lên", pronunciation: "jìn", pinyin: "jìn" },
    { chinese: "請進", mean: "mời vào (please come in)", pronunciation: "qǐng jìn", pinyin: "qǐng jìn" },
    { chinese: "醫", mean: "Y, y học, chữa bệnh.", pronunciation: "yī", pinyin: "yī" },
    { chinese: "醫生", mean: "bác sĩ", pronunciation: "yīshēng", pinyin: "yīshēng" },
    { chinese: "老", mean: "già, cũ, cổ", pronunciation: "lǎo", pinyin: "lǎo" },
    { chinese: "師", mean: "thầy; thầy dạy; thầy giáo; sư phụ", pronunciation: "shī", pinyin: "shī" },
    { chinese: "老師", mean: "giáo viên", pronunciation: "lǎoshī", pinyin: "lǎoshī" },
    { chinese: "中", mean: "chính giữa, trung tâm, Trung Quốc", pronunciation: "zhōng", pinyin: "zhōng" },
    { chinese: "中文", mean: "Tiếng Trung", pronunciation: "zhōngwén", pinyin: "zhōngwén" },
    { chinese: "中國", mean: "Trung Quốc", pronunciation: "Zhōngguó", pinyin: "Zhōngguó" },
    { chinese: "學", mean: "học, học tập", pronunciation: "xué", pinyin: "xué" },
    { chinese: "學生", mean: "Học sinh", pronunciation: "xuéshēng", pinyin: "xuéshēng" },
    { chinese: "英", mean: "Anh", pronunciation: "yīng", pinyin: "yīng" },
    { chinese: "英國", mean: "Nước Anh", pronunciation: "yīngguó", pinyin: "yīngguó" },
    { chinese: "豆", mean: "hạt đậu", pronunciation: "dòu", pinyin: "dòu" },
    { chinese: "腐", mean: "mục; mục nát; thối rữa", pronunciation: "fǔ", pinyin: "fǔ" },
    { chinese: "豆腐", mean: "Đậu phụ", pronunciation: "dòufu ", pinyin: "dòufu" },
    { chinese: "熱", mean: "nóng", pronunciation: "rè", pinyin: "rè" },
    { chinese: "熱水", mean: "Nước nóng", pronunciation: "rè shuǐ", pinyin: "rè shuǐ" },
    { chinese: "飯", mean: "Bữa ăn", pronunciation: "fàn", pinyin: "fàn" },
    { chinese: "米飯", mean: "cơm, nấu từ gạo", pronunciation: "mǐfàn", pinyin: "mǐfàn" },
    { chinese: "湯", mean: "canh, súp", pronunciation: "tāng ", pinyin: "tāng" },
    { chinese: "粥", mean: "Cháo", pronunciation: "zhōu", pinyin: "zhōu" },
    { chinese: "韓", mean: "Hàn", pronunciation: "hán", pinyin: "hán" },
    { chinese: "韓國", mean: "Hàn Quốc", pronunciation: "hánguó", pinyin: "hánguó" },
    { chinese: "數", mean: "đếm, kể ra, (Toán)", pronunciation: "shǔ", pinyin: "shǔ" },
    { chinese: "課", mean: "tiết học, giờ học, giờ lên lớp", pronunciation: "kè", pinyin: "kè" },
    { chinese: "數學課", mean: "lớp toán, tiết toán", pronunciation: "Shùxué kè", pinyin: "Shùxué kè" },
    { chinese: "上", mean: "lên; đi lên; ở trên; bắt đầu; tham gia [up / above / on]", pronunciation: "shàng", pinyin: "shàng" },
    { chinese: "下", mean: "dưới; phía dưới [down / below / under]", pronunciation: "xià", pinyin: "xià" },
    { chinese: "左", mean: "trái; bên trái (tả) [left]", pronunciation: "zuǒ", pinyin: "zuǒ" },
    { chinese: "右", mean: "bên phải; phía phải; bên tay phải (hửu) [right]", pronunciation: "yòu", pinyin: "yòu" },
    { chinese: "前", mean: "trước, phía trước [front / forward]", pronunciation: "qián", pinyin: "qián" },
    { chinese: "後", mean: "sau; phía sau; mặt sau [back / behind / after]", pronunciation: "hòu", pinyin: "hòu" },
    { chinese: "裡", mean: "bên trong; phía trong [inside]", pronunciation: "lǐ", pinyin: "lǐ" },
    { chinese: "外", mean: "ngoài; ở ngoài; bên ngoài [outside]", pronunciation: "wài", pinyin: "wài" },
    { chinese: "面", mean: "Hướng, phía, mặt / Sợi mì [surface / face / side]", pronunciation: "miàn", pinyin: "miàn" },
    { chinese: "上面", mean: "Phía trên [on top / above]", pronunciation: "shàng miàn", pinyin: "shàng miàn" },
    { chinese: "東", mean: "Hướng Đông [East]", pronunciation: "dōng", pinyin: "dōng" },
    { chinese: "西", mean: "Hướng tây [West]", pronunciation: "Xī", pinyin: "Xī" },
    { chinese: "北", mean: "Hướng bắc [North]", pronunciation: "Běi", pinyin: "Běi" },
    { chinese: "大家", mean: "Mọi người", pronunciation: "dàjiā", pinyin: "dàjiā" },
    { chinese: "大家好", mean: "Xin chào tất cả mọi người", pronunciation: "Dàjiā hǎo", pinyin: "Dàjiā hǎo" },
    { chinese: "同", mean: "Đồng (cùng; giống nhau; tương đồng; như nhau)", pronunciation: "tóng", pinyin: "tóng" },
    { chinese: "同學", mean: "Bạn học, đồng môn", pronunciation: "tóngxué", pinyin: "tóngxué" },
    { chinese: "朋", mean: "kết bè; kết phái; kéo cánh (Bạn)", pronunciation: "péng", pinyin: "péng" },
    { chinese: "友", mean: "thân cận; thân nhau; gần gũi (Bạn)", pronunciation: "yǒu", pinyin: "yǒu" },
    { chinese: "朋友", mean: "Bạn bè", pronunciation: "péngyou", pinyin: "péngyou" },
    { chinese: "男朋友", mean: "Bạn trai", pronunciation: "nánpéngyou", pinyin: "nánpéngyou" },
    { chinese: "女朋友", mean: "bạn gái; người yêu", pronunciation: "nǚpéngyou", pinyin: "nǚpéngyou" },
    { chinese: "事", mean: " việc; công việc; sự việc, sự tình", pronunciation: "shì", pinyin: "shì" },
    { chinese: "同事", mean: "Đồng nghiệp", pronunciation: "tóngshì", pinyin: "tóngshì" },
    { chinese: "戶", mean: "cửa, hộ gia đình (khách hàng -> khi ghép trong từ như 客戶)", pronunciation: "hù", pinyin: "hù" },
    { chinese: "客戶", mean: "Khách Hàng (nhấn mạnh “mối quan hệ khách hàng” thường trong hợp đồng, giao dịch, công ty)", pronunciation: "kèhù", pinyin: "kèhù" },
    { chinese: "顧", mean: "nhìn lại, ngoái lại, quan tâm, chăm sóc, để ý đến (khách khi ghép trong từ 顧客 = khách hàng)", pronunciation: "gù", pinyin: "gù" },
    { chinese: "顧客", mean: "Khách Hàng (nhấn mạnh “khách đến mua hàng, dùng dịch vụ” trực tiếp)", pronunciation: "gùkè", pinyin: "gùkè" },
    { chinese: "千", mean: "Nghìn", pronunciation: "qiān", pinyin: "qiān" },
    { chinese: "一千", mean: "Một nghìn", pronunciation: "Yīqiān", pinyin: "Yīqiān" },
    { chinese: "律", mean: "Luật, pháp luật; quy tắc [law]", pronunciation: "lǜ", pinyin: "lǜ" },
    { chinese: "律師", mean: "luật sư [lawyer]", pronunciation: "lǜshī", pinyin: "lǜshī" },
    { chinese: "第", mean: "đứng trước số để chỉ thứ tự, thứ hạng", pronunciation: "dì", pinyin: "dì" },
    { chinese: "第一", mean: "thứ nhất; hạng nhất; bậc nhất; đầu tiên; đệ nhất [first / number one]", pronunciation: "dì yī", pinyin: "dì yī" },
    { chinese: "公", mean: "công cộng, chung, công khai", pronunciation: "gōng", pinyin: "gōng" },
    { chinese: "司", mean: "quản lý, điều hành", pronunciation: "sī", pinyin: "sī" },
    { chinese: "公司", mean: "công ty [company / corporation]", pronunciation: "gōngsī", pinyin: "gōngsī" },
    { chinese: "商", mean: "thương nhân, buôn bán, thương mại", pronunciation: "shāng", pinyin: "shāng" },
    { chinese: "店", mean: "tiệm, cửa hàng nhỏ", pronunciation: "diàn", pinyin: "diàn" },
    { chinese: "商店", mean: "cửa hàng [shop, store]", pronunciation: "shāngdiàn", pinyin: "shāngdiàn" },
    { chinese: "超", mean: "siêu, vượt qua [super / exceed]", pronunciation: "chāo", pinyin: "chāo" },
    { chinese: "市", mean: "chợ, thị trường [market]", pronunciation: "shì", pinyin: "shì" },
    { chinese: "超市", mean: "Siêu thị [supermarket]", pronunciation: "chāoshì", pinyin: "chāoshì" },
    { chinese: "館", mean: "quán, nhà, phòng", pronunciation: "guǎn", pinyin: "guǎn" },
    { chinese: "飯館", mean: "quán ăn, quán cơm (bình dân)", pronunciation: "fànguǎn", pinyin: "fànguǎn" },
    { chinese: "街", mean: "phố; đường phố [street]", pronunciation: "jiē", pinyin: "jiē" },
    { chinese: "街上", mean: "trên phố; trên đường [on the street]", pronunciation: "jiēshang", pinyin: "jiēshang" },
    { chinese: "昨", mean: "hôm qua; ngày hôm qua, đã qua; trước kia; trước đây; ngày xưa (thường không đi lẻ 1 mình)", pronunciation: "zuó", pinyin: "zuó" },
    { chinese: "天", mean: "thiên, trời, ngày, hôm", pronunciation: "tiān", pinyin: "tiān" },
    { chinese: "昨天", mean: "Ngày hôm qua [yesterday]", pronunciation: "zuótiān", pinyin: "zuótiān" },
    { chinese: "今", mean: "nay; hôm nay, hiện đại; ngày nay; thời nay", pronunciation: "jīn", pinyin: "jīn" },
    { chinese: "今天", mean: "Ngày hôm nay [today]", pronunciation: "jīn", pinyin: "jīn" },
    { chinese: "明", mean: "Minh (làm rõ, sáng tỏ, hiểu biết), Trong chỉ thời gian: nghĩa là ngày tới, ngày sau.", pronunciation: "míng", pinyin: "míng" },
    { chinese: "明天", mean: "Ngày mai [tomorrow]", pronunciation: "míngtiān", pinyin: "míngtiān" },
    { chinese: "週", mean: "Tuần, vòng; quanh; xung quanh", pronunciation: "zhōu", pinyin: "zhōu" },
    { chinese: "上週", mean: "Tuần trước", pronunciation: "shàng zhōu", pinyin: "shàng zhōu" },
    { chinese: "這週", mean: "Tuần này", pronunciation: "Zhè zhōu", pinyin: "Zhè zhōu" },
    { chinese: "下週", mean: "Tuần sau", pronunciation: "xià zhōu", pinyin: "xià zhōu" },
    { chinese: "末", mean: "cuối, kết thúc, ngọn; ngọn cây; đầu mút [end]", pronunciation: "mò", pinyin: "mò" },
    { chinese: "週末", mean: "cuối tuần [weekend]", pronunciation: "zhōumò", pinyin: "zhōumò" },
    { chinese: "點", mean: "giờ, điểm, chấm", pronunciation: "diǎn", pinyin: "diǎn" },
    { chinese: "三點", mean: "Ba giờ", pronunciation: "Sān diǎn", pinyin: "" },
    { chinese: "分", mean: "phút, đơn vị đồng xu, phân chia [minute]", pronunciation: "fēn", pinyin: "fēn" },
    { chinese: "二十分", mean: "Hai mươi phút", pronunciation: "Èrshí fēn", pinyin: "Èrshí fēn" },
    { chinese: "秒", mean: "giây", pronunciation: "miǎo", pinyin: "miǎo" },
    { chinese: "十秒", mean: "Mười giây", pronunciation: "Shí miǎo", pinyin: "Shí miǎo" },
    { chinese: "號", mean: "Ngày, dùng hằng ngày để nói ngày trong tháng (dùng sau số). tên hiệu; bí danh; biệt hiệu", pronunciation: "hào", pinyin: "hào" },
    { chinese: "九號", mean: "Ngày chín", pronunciation: "Jiǔ hào", pinyin: "Jiǔ hào" },
    { chinese: "月", mean: "Tháng, mặt trăng", pronunciation: "yuè", pinyin: "yuè" },
    { chinese: "年", mean: "Năm, niên", pronunciation: "nián", pinyin: "nián" },
    { chinese: "二零二五年", mean: "Năm 2025", pronunciation: "Èr líng èrwǔ nián", pinyin: "Èr líng èrwǔ nián" },
    { chinese: "去", mean: "rời; rời bỏ; rời khỏi; rời đi", pronunciation: "qù", pinyin: "qù" },
    { chinese: "去年", mean: "năm ngoái; năm qua; năm rồi; năm trước", pronunciation: "qùnián", pinyin: "qùnián" },
    { chinese: "今年", mean: "Năm nay", pronunciation: "jīnnián", pinyin: "jīnnián" },
    { chinese: "明年", mean: "Năm tới, năm sau", pronunciation: "jīnnián", pinyin: "jīnnián" },
    { chinese: "午", mean: "trưa; buổi trưa, giờ Ngọ", pronunciation: "wǔ", pinyin: "wǔ" },
    { chinese: "上午", mean: "Buổi sáng", pronunciation: "shàngwǔ", pinyin: "shàngwǔ" },
    { chinese: "中午", mean: "Buổi trưa", pronunciation: "zhōngwǔ", pinyin: "zhōngwǔ" },
    { chinese: "下午", mean: "buổi chiều", pronunciation: "xiàwǔ", pinyin: "xiàwǔ" },
    { chinese: "晚", mean: "Muộn, tối", pronunciation: "wǎn", pinyin: "wǎn" },
    { chinese: "晚上", mean: "buổi tối", pronunciation: "wǎnshang", pinyin: "wǎnshang" },
    { chinese: "白天", mean: "Ban ngày", pronunciation: "báitiān", pinyin: "báitiān" },
    { chinese: "夜", mean: "Đêm, đêm khuya", pronunciation: "yè", pinyin: "yè" },
    { chinese: "夜裡", mean: "Ban đêm", pronunciation: "yèlǐ", pinyin: "yèlǐ" },
    { chinese: "少", mean: "ít", pronunciation: "shǎo", pinyin: "shǎo" },
    { chinese: "說", mean: "nói, kể", pronunciation: "shuō", pinyin: "shuō" },
    { chinese: "狗", mean: "Con chó", pronunciation: "gǒu", pinyin: "gǒu" },
    { chinese: "貓", mean: "Con mèo", pronunciation: "māo ", pinyin: "māo" },
    { chinese: "星", mean: "sao; ngôi sao", pronunciation: "xīng", pinyin: "xīng" },
    { chinese: "期", mean: "kỳ; chu kỳ; thời kỳ", pronunciation: "qī", pinyin: "qī" },
    { chinese: "星期一", mean: "Thứ hai [monday] văn nói", pronunciation: "xīngqī yī", pinyin: "xīngqī yī" },
    { chinese: "週一", mean: "Thứ hai [monday] văn viết", pronunciation: "zhōuyī", pinyin: "zhōuyī" },
    { chinese: "星期二", mean: "Thứ ba [tuesday] văn nói", pronunciation: "xīngqī èr", pinyin: "xīngqī èr" },
    { chinese: "週二", mean: "Thứ ba [tuesday] văn viết", pronunciation: "zhōu'èr", pinyin: "zhōu'èr" },
    { chinese: "星期三", mean: "Thứ tư [wednesday] văn nói", pronunciation: "xīngqī sān", pinyin: "xīngqī sān" },
    { chinese: "週三", mean: "Thứ tư [wednesday] văn viết", pronunciation: "zhōusān", pinyin: "zhōusān" },
    { chinese: "星期四", mean: "Thứ năm [thursday] văn nói", pronunciation: "xīngqī sì", pinyin: "xīngqī sì" },
    { chinese: "週四", mean: "Thứ năm [thursday] văn viết", pronunciation: "zhōusì", pinyin: "zhōusì" },
    { chinese: "星期五", mean: "Thứ sáu [friday] văn nói", pronunciation: "xīngqī wǔ", pinyin: "xīngqī wǔ" },
    { chinese: "週五", mean: "Thứ sáu [friday] văn viết", pronunciation: "zhōuwǔ", pinyin: "zhōuwǔ" },
    { chinese: "星期六", mean: "Thứ bảy [saturday] văn nói", pronunciation: "xīngqī liù", pinyin: "xīngqī liù" },
    { chinese: "週六", mean: "Thứ bảy [saturday] văn viết", pronunciation: "zhōuliù", pinyin: "zhōuliù" },
    { chinese: "星期日", mean: "Chủ nhật [sunday] văn nói", pronunciation: "xīngqī rì", pinyin: "xīngqī rì" },
    { chinese: "週日", mean: "Chủ nhật [sunday] văn viết", pronunciation: "zhōurì", pinyin: "zhōurì" },
    { chinese: "色", mean: "màu; màu sắc [color]", pronunciation: "sè", pinyin: "sè" },
    { chinese: "黑", mean: "Đen [black]", pronunciation: "hēi", pinyin: "hēi" },
    { chinese: "黑色", mean: "màu đen [black color]", pronunciation: "hēisè", pinyin: "hēisè" },
    { chinese: "紅", mean: "Đỏ [red]", pronunciation: "hóng", pinyin: "hóng" },
    { chinese: "藍", mean: "Xanh dương [blue]", pronunciation: "lán", pinyin: "lán" },
    { chinese: "綠", mean: "xanh; xanh lục; xanh lá cây [green]", pronunciation: "lǜ", pinyin: "lǜ" },
    { chinese: "黃", mean: "vàng [yellow]", pronunciation: "huáng", pinyin: "huáng" },
    { chinese: "橙", mean: "cam, màu cam, quả cam [orange]", pronunciation: "chéng", pinyin: "chéng" },
    { chinese: "紫", mean: "tím [purple]", pronunciation: "zǐ", pinyin: "zǐ" },
    { chinese: "咖啡色", mean: "Màu nâu [brown] văn nói", pronunciation: "kāfēisè", pinyin: "kāfēisè" },
    { chinese: "棕", mean: "Cây cọ/Màu nâu [brown] văn viết", pronunciation: "zōng", pinyin: "zōng" },
    { chinese: "灰", mean: "Xám, tro; tàn; than; bụi [grey]", pronunciation: "huī", pinyin: "huī" },
    { chinese: "粉", mean: "phấn; bụi; bột", pronunciation: "fěn", pinyin: "fěn" },
    { chinese: "粉紅", mean: "màu hồng nhạt; màu hồng phấn [pink]", pronunciation: "fěnhóng", pinyin: "fěnhóng" },
    { chinese: "新", mean: "Mới [new]", pronunciation: "xīn", pinyin: "xīn" },
    { chinese: "舊", mean: "cũ; xưa [old]", pronunciation: "jiù", pinyin: "jiù" },
    { chinese: "高", mean: "Cao [tall, high]", pronunciation: "gāo", pinyin: "gāo" },
    { chinese: "低", mean: "Thấp [low]", pronunciation: "dī", pinyin: "dī" },
    { chinese: "小", mean: "Nhỏ [small]", pronunciation: "xiǎo", pinyin: "xiǎo" },
    { chinese: "長", mean: "Dài [long]", pronunciation: "cháng", pinyin: "cháng" },
    { chinese: "短", mean: "Ngắn [short]", pronunciation: "duǎn", pinyin: "duǎn" },
    { chinese: "快", mean: "Nhanh [fast, quick]", pronunciation: "kuài", pinyin: "kuài" },
    { chinese: "慢", mean: "Chậm [slow]", pronunciation: "màn", pinyin: "màn" },
    { chinese: "早", mean: "Sớm [early]", pronunciation: "zǎo", pinyin: "zǎo" },
    { chinese: "棒", mean: "Giỏi, xuất sắc [excellent, great]", pronunciation: "bàng", pinyin: "bàng" },
    { chinese: "差", mean: "Tệ, kém, dở [bad, poor]", pronunciation: "chà", pinyin: "chà" },
    { chinese: "醜", mean: "Xấu [ugly]", pronunciation: "chǒu", pinyin: "chǒu" },
    { chinese: "勤", mean: "Siêng, chăm chỉ [diligent]", pronunciation: "qín", pinyin: "qín" },
    { chinese: "勤快", mean: "Siêng năng, chăm chỉ [hardworking]", pronunciation: "qínkuài", pinyin: "qínkuài" },
    { chinese: "懶", mean: "Lười [lazy]", pronunciation: "lǎn", pinyin: "lǎn" },
    { chinese: "閒", mean: "Rảnh [free, idle]", pronunciation: "xián", pinyin: "xián" },
    { chinese: "富", mean: "Giàu [rich]", pronunciation: "fù", pinyin: "fù" },
    { chinese: "窮", mean: "Nghèo [poor]", pronunciation: "qióng", pinyin: "qióng" },
    { chinese: "活", mean: "Sống [live, alive]", pronunciation: "huó", pinyin: "huó" },
    { chinese: "死", mean: "Chết [die]", pronunciation: "sǐ", pinyin: "sǐ" },
];