/*******************************
 * 1) DỮ LIỆU TỪ VỰNG (ví dụ)
 * Thay/ví dụ bằng 1000 từ của bạn.
 *******************************/
const vocabulary = [
    { chinese: "你好", mean: "Xin chào", pronunciation: "Nỉ hảo", pinyin: "Nǐ hǎo" },
//   { chinese: "谢谢", mean: "Cảm ơn", pronunciation: "Xiè xiè", pinyin: "Xièxie" },
//   { chinese: "再见", mean: "Tạm biệt", pronunciation: "Chai chiện", pinyin: "Zàijiàn" },
//   { chinese: "请", mean: "Làm ơn / Mời", pronunciation: "Chǐng", pinyin: "Qǐng" },
//   { chinese: "对不起", mean: "Xin lỗi", pronunciation: "Tuây pu chỉ", pinyin: "Duìbùqǐ" },
//   { chinese: "没关系", mean: "Không sao", pronunciation: "Mấy quan xi", pinyin: "Méi guānxi" },
//   { chinese: "早上好", mean: "Chào buổi sáng", pronunciation: "Zảo shàng hảo", pinyin: "Zǎoshang hǎo" },
//   { chinese: "晚上好", mean: "Chào buổi tối", pronunciation: "Uẳn shàng hảo", pinyin: "Wǎnshang hǎo" },
//   { chinese: "请问", mean: "Cho hỏi", pronunciation: "Chǐng uấn", pinyin: "Qǐngwèn" },
//   { chinese: "厕所", mean: "Nhà vệ sinh", pronunciation: "Thứa sủa", pinyin: "Cèsuǒ" },
//   { chinese: "", mean: "", pronunciation: "", pinyin: "" },
//   ... thêm tiếp cho đến 1000 mục
//    { chinese: "", mean: "", pronunciation: "", pinyin: "" },
    { chinese: "一", mean: "Số một", pronunciation: "Di", pinyin: "Yī" },
    { chinese: "二", mean: "Số hai", pronunciation: "Ơ", pinyin: "Èr" },
    { chinese: "三", mean: "Số ba", pronunciation: "San", pinyin: "Sān" },
    { chinese: "四", mean: "Số bốn", pronunciation: "Sư", pinyin: "Sì" },
    { chinese: "五", mean: "Số năm", pronunciation: "Ủ", pinyin: "wǔ" },
    { chinese: "六", mean: "Số sáu", pronunciation: "liu ồ", pinyin: "liù" },
    { chinese: "七", mean: "Số bảy", pronunciation: "Chi", pinyin: "qī" },
    { chinese: "八", mean: "Số tám", pronunciation: "Ba", pinyin: "bā" },
    { chinese: "九", mean: "Số Chín", pronunciation: "chổ", pinyin: "jiǔ" },
    { chinese: "十", mean: "Số mười", pronunciation: "sử", pinyin: "shí" },
    { chinese: "十一", mean: "Mười một", pronunciation: "Sử di", pinyin: "Shíyī" },
    { chinese: "二十", mean: "Hai mươi", pronunciation: "Ơ sử", pinyin: "Èrshí" },
    { chinese: "三十", mean: "Ba mươi", pronunciation: "San sử", pinyin: "Sānshí" },
    { chinese: "四十", mean: "Bốn mươi", pronunciation: "Sư sử", pinyin: "Sìshí" },
    { chinese: "五十", mean: "Năm mươi", pronunciation: "Ủ sử", pinyin: "Wǔshí" },
    { chinese: "六十", mean: "Sáu mươi", pronunciation: "Liêu sử", pinyin: "Liùshí" },
    { chinese: "七十", mean: "Bảy mươi", pronunciation: "Chi sử", pinyin: "Qīshí" },
    { chinese: "八十", mean: "Tám mươi", pronunciation: "Ba sử", pinyin: "Bāshí" },
    { chinese: "九十", mean: "Chín mươi", pronunciation: "Chiu sử", pinyin: "Jiǔshí" },
    { chinese: "一百", mean: "Một trăm", pronunciation: "I bải", pinyin: "Yībǎi" },
    { chinese: "一百零一", mean: "Một trăm lẻ một", pronunciation: "I bải líng i", pinyin: "Yībǎi líng yī" },
    { chinese: "一百一十一", mean: "Một trăm mười một", pronunciation: "I bải i sư i", pinyin: "Yībǎi yīshí yī" },
    { chinese: "大", mean: "To lớn", pronunciation: "Ta", pinyin: "Dà" },
    { chinese: "口", mean: "Cái miệng", pronunciation: "Câu ồ", pinyin: "Kǒu" },
    { chinese: "白", mean: "Màu trắng", pronunciation: "Bái", pinyin: "Bái" },
    { chinese: "不", mean: "Không", pronunciation: "Bu", pinyin: "Bù" },
    { chinese: "马", mean: "Con ngựa", pronunciation: "Mạ", pinyin: "Mǎ" },
    { chinese: "女", mean: "Nữ giới", pronunciation: "Nủy", pinyin: "Nǚ" },
    { chinese: "你", mean: "Bạn/cậu/mày", pronunciation: "Nỉ", pinyin: "Nǐ" },
    { chinese: "男", mean: "Nam giới", pronunciation: "Nán", pinyin: "Nán" },
    { chinese: "忙", mean: "Bận", pronunciation: "máng", pinyin: "Máng" },
    { chinese: "吗", mean: "Trợ từ nghi vấn/ ...không?", pronunciation: "Ma", pinyin: "Ma" },
    { chinese: "很", mean: "rất", pronunciation: "Hen", pinyin: "Hěn" },
    { chinese: "汉", mean: "Chữ Hán/dân tộc Hán/ Trung quốc", pronunciation: "Han", pinyin: "Hàn" },
    { chinese: "语", mean: "Ngữ/ngôn ngữ", pronunciation: "Dĩ", pinyin: "Yǔ" },
    { chinese: "太", mean: "quá", pronunciation: "Tai", pinyin: "Tài" },
    { chinese: "爸爸", mean: "Bố/ba", pronunciation: "Ba bà", pinyin: "Bàba" },
    { chinese: "妈妈", mean: "Mẹ", pronunciation: "Ma mà", pinyin: "妈妈" },
    { chinese: "哥哥", mean: "Anh trai", pronunciation: "Cưa cừa", pinyin: "Gēgē" },
    { chinese: "弟弟", mean: "Em trai", pronunciation: "Đi đì", pinyin: "Dìdì" },
    { chinese: "姐姐", mean: "Chị gái", pronunciation: "Chìa chia", pinyin: "Jiějiě" },
    { chinese: "妹妹", mean: "Em gái", pronunciation: "Mây mầy", pinyin: "Mèimei" },
    { chinese: "他", mean: "Anh ấy, ông ấy, chú ấy", pronunciation: "Ta", pinyin: "Tā" },
    { chinese: "她 ", mean: "Chị ấy, bà ấy, cô ấy", pronunciation: "Ta", pinyin: "Tā" },
    { chinese: "的", mean: "Của", pronunciation: "Đơ", pinyin: "de" },

];